# docker-compose-dev.yml - Docker compose specification for development environment
# Subzeero (Zander Rommelaere)
# January 16, 2024

version: "3.9"
services:
  node-back:
    build: .
    container_name: node-back
    ports:
      - 4000:4000
    volumes:
      - ./backend:/opt/backend/mnt
    environment:
      - CONTAINER_TYPE=backend
      - DEV_MODE=true
      - PGUSER=root
      - PGPASSWORD=root
      - PGHOST=postgresql
      - PGDATABASE=domain-root-site
    depends_on:
      postgresql:
        condition: service_started
    stdin_open: true
    tty: true

  node-front:
    build: .
    container_name: node-front
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/opt/frontend/mnt
    environment:
      - CONTAINER_TYPE=frontend
      - DEV_MODE=true
    depends_on:
      postgresql:
        condition: service_started
      node-back:
        condition: service_started
    stdin_open: true
    tty: true

  postgresql:
    image: postgres:16
    container_name: postgresql
    volumes:
      - ./backend/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=domain-root-site
