# docker-compose.yml - Docker compose specification for production environment
# Subzeero (Zander Rommelaere)
# January 16, 2024

# Ensure these placeholder credential values are replaced with
# secure variants for deployment

version: "3.9"
services:
  node-back:
    build: .
    container_name: node-back
    ports:
      - 4000:4000
    environment:
      - CONTAINER_TYPE=backend
      - PGUSER=root
      - PGPASSWORD=root
      - PGHOST=postgresql
      - PGDATABASE=domain-root-site
    depends_on:
      postgresql:
        condition: service_started

  node-front:
    build: .
    container_name: node-front
    ports:
      - 3000:3000
    environment:
      - CONTAINER_TYPE=frontend
    depends_on:
      postgresql:
        condition: service_started
      node-back:
        condition: service_started

  postgresql:
    image: postgres:16
    container_name: postgresql
    volumes:
      - ./backend/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=domain-root-site
