name: Build and Publish Image

on:
  push:
    branches: ["main"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GH Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            subzeero/domain-root-site:latest
            subzeero/domain-root-site:$(git rev-parse --short "$GITHUB_SHA")
            ghcr.io/subzeero/domain-root-site:latest
            ghcr.io/subzeero/domain-root-site:$(git rev-parse --short "$GITHUB_SHA")
          cache-from: type=registry,ref=subzeero/domain-root-site:latest
          cache-to: type=inline
